// <auto-generated />
using System;
using HaefeleSoftware.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaefeleSoftware.Api.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240615220554_Initial_v1")]
    partial class Initial_v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HaefeleSoftware.Api.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("created")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("created_by")
                        .HasColumnOrder(3);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified")
                        .HasColumnOrder(2);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("last_modified_by")
                        .HasColumnOrder(4);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles", "dbo");
                });

            modelBuilder.Entity("HaefeleSoftware.Api.Domain.Entities.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("created")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("created_by")
                        .HasColumnOrder(3);

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAt")
                        .HasMaxLength(100)
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<int>("FK_UserId")
                        .HasColumnType("int")
                        .HasColumnName("fk_user_id");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit")
                        .HasColumnName("is_expired");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("LastModified")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified")
                        .HasColumnOrder(2);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("last_modified_by")
                        .HasColumnOrder(4);

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("refresh_token");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("revoked_by_ip");

                    b.HasKey("Id");

                    b.HasIndex("FK_UserId");

                    b.ToTable("tokens", "dbo");
                });

            modelBuilder.Entity("HaefeleSoftware.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("created")
                        .HasColumnOrder(1);

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("created_by")
                        .HasColumnOrder(3);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("email");

                    b.Property<int>("FK_RoleId")
                        .HasColumnType("int")
                        .HasColumnName("fk_role_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2")
                        .HasColumnName("last_modified")
                        .HasColumnOrder(2);

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("last_modified_by")
                        .HasColumnOrder(4);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("FK_RoleId");

                    b.ToTable("users", "dbo");
                });

            modelBuilder.Entity("HaefeleSoftware.Api.Domain.Entities.Token", b =>
                {
                    b.HasOne("HaefeleSoftware.Api.Domain.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("FK_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HaefeleSoftware.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("HaefeleSoftware.Api.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("FK_RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HaefeleSoftware.Api.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HaefeleSoftware.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
